// <auto-generated />
namespace UppgraderingAdressBok.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201711031931527_EmmasAdressBok : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201711031931527_EmmasAdressBok));
        
        string IMigrationMetadata.Id
        {
            get { return "201711052041292_201711031931527_EmmasAdressBok"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
